
#服务端口配置
server:
  port: 9500

spring:
  application:
    name: bootTest
  #数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/boottest?useSSL=true&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true&serverTimezone=GMT
    username: root
    password: 123456
    #driver-class-name: com.mysql.jdbc.Driver

  #mvc配置
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  #redis配置
  redis:
    database: 0
    host: localhost
    port: 6379
    jedis:
      pool:
        max-active: 20

#服务注册配置
eureka:
  client:
    #可将自身当做服务
    register-with-eureka: true
    fetch-registry: true
    #客户端的健康检查
    healthcheck:
      enabled: true
    #指定客户端对应的注册中心服务器的地址
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    #注册到注册中心的是IP
    prefer-ip-address: false
    hostname: www.baidu.com
    #hostname:

##日志配置
#logging:
#  config: classpath:log4j2.xml
